# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47c38801d644fffcf88232aeee72136dbc07edcfedbcca90021b3e3639faae8c7a811767557c927599313c4b30f277a4b9bcd2b4824a09ec2141bca148d4075

test:
  secret_key_base: 42c12a31b8b1defca42d336d626a0839c42f758187c7f2cbce934599c3a525a3e933aba41c95eb35d3f99c94750bfab89e70b70865f410206e61c30e1e3575aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
